version: "3.1"
services:
    watcher:
        image: "nimashoghi/configurator-server:latest"
        env_file:
            - ./.env
        volumes:
            - ./settings.json:/app/settings.json
        ports:
            - "80:80"
        restart: always
        stdin_open: true
        tty: true
