version: "3.1"
services:
    configurator:
        image: "nimashoghi/configurator-server:latest"
        environment:
            - SCHEMA_FILE=/app/settings.schema.json
            - SETTINGS_FILE=/app/settings.json
            - UPDATE_PASSWORD=wG6gIvi7jE49yaNH5gRbNMCiUvcTn5IOCClsIPhcwkysE1i63wM41hml8GdRTTT6
        volumes:
            - ./settings.json:/app/settings.json
            - ./settings.schema.json:/app/settings.schema.json
        ports:
            - "80:80"
